ci: retry tf apply upto three times

diff --git a/.github/workflows/tf_apply.yaml b/.github/workflows/tf_apply.yaml
--- a/.github/workflows/tf_apply.yaml
+++ b/.github/workflows/tf_apply.yaml
@@ -46,9 +46,8 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
+          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v4
@@ -60,6 +59,8 @@ jobs:
         run: |
           terraform init \
             -backend-config=../../backend/${TF_ENV}.tfbackend
+          terraform fmt -check -recursive
+          terraform validate
 
       # - name: Terraform Format Check
       #   working-directory: ${{ env.TF_DIR }}
@@ -142,4 +143,19 @@ jobs:
 
       - name: Terraform Apply
         working-directory: ${{ env.TF_DIR }}
-        run: terraform apply -auto-approve tfplan
+        run: |
+          for attempt in 1 2 3; do
+            if terraform apply -auto-approve tfplan; then
+             break
+            fi
+
+            if [ "$attempt" -eq 3 ]; then
+              echo "Apply failed after 3 attempts"
+              exit 1
+            fi
+
+            echo "Apply failed (attempt $attempt/3), retrying in 30s..."
+            sleep 30
+          done
+      
+      
diff --git a/.github/workflows/tf_destroy.yaml b/.github/workflows/tf_destroy.yaml
--- a/.github/workflows/tf_destroy.yaml
+++ b/.github/workflows/tf_destroy.yaml
@@ -132,6 +132,21 @@ jobs:
       - name: Terraform Apply Destroy
         working-directory: ${{ env.TF_DIR }}
         run: |
-          terraform apply \
-            -auto-approve \
-            destroy.tfplan
+          # terraform apply \
+          #   -auto-approve \
+          #   destroy.tfplan
+          for attempt in 1 2 3; do
+            if terraform apply --auto-approve destroy.tfplan; then
+              break
+            fi
+
+            if [ "$attempt" -eq 3 ]; then
+              echo "Destroy failed after 3 attempts"
+              exit 1
+            fi
+
+            echo "Destroy failed (attempt $attempt/3), retrying in 30s..."
+            sleep 30
+          done
+          
+            
